server:
  port: 9090

spring:
  application:
    name: Payment_Gateway_Service_1.0.3

  datasource:
    url: jdbc:mysql://localhost:3306/Treasurex_Payment_Gateway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
razorpay:
  keyId: rzp_test_RWu7WwWwg3nhHn
  keySecret: 9EzQmbYq1zSTy3UYJtQ1juW2