server:
  port: 9090

spring:
  application:
    name: Treasurex Login Service

  datasource:
    url: jdbc:mysql://localhost:3306/Treasurex_One?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: imnavi9999@gmail.com
    password: axlo gwlk pxjx rjmt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        
#logging:
# level:
#   root: OFF